### ISSUE TITLE
PVOutput Upload

### ISSUE THREAD

**Issue by mildlyill** [ClassicDIY/Classic#5]
Hi there,

First I'd like to say great work on the app, it's been fantastic for me. I have a classic 150 with 500 watts of panels and I wanted to see how things look on PVOutput.org.

Yesterday I created my account and set the app up with the API key and Site ID, but I'm not seeing any outputs recorded on the site. I also tried generating another API key last night, still nothing.

Is there any way to check a log or something to see what's happening?

Thanks!

**Comment by graham22** [comment]
Thanks,
Make sure your classic has its date set correctly.
Enter the Sid while the app is connected to the classic.
Clear the recorded log (bottom of settings dialog)
Shutdown and restart the app, connect to the classic, let it run for a few
minutes.

If it still doesn't work. Try again tomorrow since pvoutput has a limit of
20 transactions a day at a rate of one every 10 seconds
